-- MySQL Script generated by MySQL Workbench
-- Wed Jun 21 08:56:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `Chip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Chip` (
  `idChip` INT NOT NULL,
  `codigoChip` VARCHAR(45) NOT NULL,
  `dataAplicacao` DATE NOT NULL,
  PRIMARY KEY (`idChip`),
  UNIQUE INDEX `codigoChip_UNIQUE` (`codigoChip` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tutor` (
  `idTutor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Animal` (
  `idAnimal` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `peso` FLOAT NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `anoNascimento` INT NOT NULL,
  `tipoAnimal` ENUM('G', 'C', 'O') NOT NULL,
  `idChip` INT NULL,
  `idTutor` INT NOT NULL,
  PRIMARY KEY (`idAnimal`),
  INDEX `fk_Animal_ChipIdentificacao1_idx` (`idChip` ASC) VISIBLE,
  INDEX `fk_Animal_Tutor1_idx` (`idTutor` ASC) VISIBLE,
  CONSTRAINT `fk_Animal_ChipIdentificacao1`
    FOREIGN KEY (`idChip`)
    REFERENCES `Chip` (`idChip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animal_Tutor1`
    FOREIGN KEY (`idTutor`)
    REFERENCES `Tutor` (`idTutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
