-- MySQL Script generated by MySQL Workbench
-- Mon May 12 09:04:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema a202440602003
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema a202440602003
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `a202440602003` DEFAULT CHARACTER SET utf8 ;
USE `a202440602003` ;

-- -----------------------------------------------------
-- Table `a202440602003`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a202440602003`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `nomeCategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a202440602003`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a202440602003`.`Produto` (
  `idProduto` INT NOT NULL,
  `nomeProduto` VARCHAR(45) NOT NULL,
  `precoProduto` FLOAT UNSIGNED NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_Produto_Categoria_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Categoria`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `a202440602003`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
